### Перемножение матриц

In [22]:
import numpy as np

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """
    size = len(first)
    new_arr = []
    for f_lines in range(size):
        new_line = []
        for s_columns in range(size):
            s = 0
            for s_line_elem in range(size):
                s_elem = second[s_line_elem][s_columns]
                s += s_elem * first[f_lines][s_line_elem]
            new_line.append(s)

        new_arr.append(new_line)
        
    result = new_arr
    return result

def numpy_mult(first, second):
    """
    param first: np.array[size, size]
    param second: np.array[size, size]
    """

    result = first @ second
    return result


In [18]:
import numpy as np

def no_numpy_mult(first, second):
    """
    param first: list of "size" lists, each contains "size" floats
    param first: list of "size" lists, each contains "size" floats
    """
    size = len(first)
    new_arr = []
    for f_lines in range(size):
        new_line = []
        for s_columns in range(size):
            s = 0
            for s_line_elem in range(size):
                s_elem = second[s_line_elem][s_columns]
                s += s_elem * first[f_lines][s_line_elem]
            new_line.append(s)

        new_arr.append(new_line)
        
    result = new_arr
    return result

In [19]:
f = [[4, -1, 3], [4, -2 , -6], [2, 0, 3]]
s = [[5, 3, -7], [-1, 6 , -3], [2, -4, 1]]
a = no_numpy_mult(f, s)
print(a[0])
print(a[1])
print(a[2])

[27, -6, -22]
[10, 24, -28]
[16, -6, -11]


In [24]:
numpy_mult(np.array(f),np.array(s))

array([[ 27,  -6, -22],
       [ 10,  24, -28],
       [ 16,  -6, -11]])

### Два вектора в трехмерном пространстве

In [29]:
import numpy as np

def no_numpy_scalar(v1, v2):
    result = []
    for i, el1 in enumerate(v1):
        result.append(el1 * v2[i])
        
    return result

def numpy_scalar (v1, v2):
    result = v1 @ v2
    return result

In [30]:
a = [1, 2, 3]
b = [5, 6, 7]
no_numpy_scalar(a, b)

[5, 12, 21]

In [31]:
numpy_scalar(np.array(a), np.array(b))

38

In [32]:
np.inner(a, b)

38

### Главная диаоганаль

In [49]:
import numpy as np         

def diag_2k(a):
    b = np.diag(a)

    result = b[b % 2 == 0].sum()
    return result

In [45]:
a = np.array([[6,2,3],[4,2,6],[7,8,9]])
a

array([[6, 2, 3],
       [4, 2, 6],
       [7, 8, 9]])

In [48]:
b = np.diag(a)
b[b % 2 == 0].sum()

8

In [47]:
b[b % 2 == 0]

array([6, 2])

### Матрица и частичные суммы

In [ ]:
import numpy as np

def cumsum(A):
    np.cumsum(a, axis = 1)

    result = #YOUR CODE
    return result

In [50]:
a = np.array([[6,2,3],[4,2,6],[7,8,9]])
a

array([[6, 2, 3],
       [4, 2, 6],
       [7, 8, 9]])

In [52]:
np.cumsum(a, axis = 1)

array([[ 6,  8, 11],
       [ 4,  6, 12],
       [ 7, 15, 24]], dtype=int32)

### Склеивание

In [120]:
import numpy as np

def transform(X, a=1):
    """
    param X: np.array[batch_size, n]
    """
    result = []
    for A in X:
        B = np.copy(A)
        B[1::2] = a
        B[::2] = B[::-2]**3
        result.append(np.concatenate([A, B]))
    
    return np.array(result)

In [121]:
a = np.array([[6,2,3],[4,2,6],[7,8,9]])
a

array([[6, 2, 3],
       [4, 2, 6],
       [7, 8, 9]])

In [122]:
transform(a)

array([[  6,   2,   3,  27,   1, 216],
       [  4,   2,   6, 216,   1,  64],
       [  7,   8,   9, 729,   1, 343]])

### Run-length encoding

In [130]:
import numpy as np

def encode(a):
    #YOUR CODE

    #result = #YOUR CODE
    return result

In [129]:
import numpy as np
a = np.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
unique, counts = np.unique(a, return_counts=True)
dict(zip(unique, counts))

# {0: 7, 1: 4, 2: 1, 3: 2, 4: 1}

{0: 7, 1: 4, 2: 1, 3: 2, 4: 1}